CREATE DATABASE MUSICALLY;

USE MUSICALLY;

CREATE TABLE USERS (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME TEXT NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE SONGS (
  ID VARCHAR(24) NOT NULL,
  NAME TEXT NOT NULL,
  ARTIST TEXT NOT NULL,
  ALBUM TEXT NOT NULL,
  ALBUM_IMAGE_URL TEXT NOT NULL,
  POPULARITY INT NOT NULL,
  EXPLICIT BOOLEAN NOT NULL,
  URL TEXT NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE USERS_FAVORITES (
  ID INT NOT NULL AUTO_INCREMENT,
  USER_ID INT NOT NULL,
  SONG_ID VARCHAR(24) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (USER_ID)
    REFERENCES USERS(ID),
  FOREIGN KEY (SONG_ID)
    REFERENCES SONGS(ID)
);

CREATE TABLE USERS_PLAYS (
  ID INT NOT NULL AUTO_INCREMENT,
  USER_ID INT NOT NULL,
  SONG_ID VARCHAR(24) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (USER_ID)
    REFERENCES USERS(ID),
  FOREIGN KEY (SONG_ID)
    REFERENCES SONGS(ID)
);

INSERT INTO USERS (NAME) VALUES ('Chris');